# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
# NadPay Indexer Configuration - Monad Testnet
name: envio-indexer
networks:
- id: 41004
  rpc: https://testnet-rpc.monad.xyz
  start_block: 3000000
  contracts:
  - name: NadPay
    address:
    - 0xa81F9ED8cf8030424F049b385a1dB32cA504177d
    handler: src/EventHandlers.ts
    events:
    - event: PaymentLinkCreated(uint256 indexed linkId, address indexed creator, uint256 price, string title, string description)
    - event: PurchaseMade(uint256 indexed linkId, address indexed buyer, uint256 amount, uint256 totalPrice)
  - name: NadRaffle
    address:
    - 0x5007131517440FEEf9F67291A35E4100c41f3aB5
    handler: src/EventHandlers.ts
    events:
    - event: RaffleCreated(uint256 indexed raffleId, address indexed creator, string title, string description, uint256 ticketPrice, uint256 endTime, address rewardTokenAddress, uint256 rewardAmount, uint8 rewardType)
    - event: RaffleEnded(uint256 indexed raffleId, address winner, uint256 totalTickets, uint256 totalAmount)
    - event: RewardClaimed(uint256 indexed raffleId, address indexed winner, uint256 rewardAmount)
    - event: TicketPurchased(uint256 indexed raffleId, address indexed buyer, uint256 amount)
unordered_multichain_mode: true
