# Cache bust: 1735831100
[phases.setup]
nixPkgs = ['nodejs-18_x', 'python39']

[phases.install]
cmds = [
    'npm install -g pm2',
    'npm ci --omit=dev --prefer-offline --no-audit --no-fund --legacy-peer-deps'
]
cacheDirectories = ['/root/.npm']

[phases.build]
cmds = [
    'npm run build'
]
cacheDirectories = ['/app/.next/cache']

[start]
cmd = 'pm2-runtime start ecosystem.config.js'

[variables]
NODE_ENV = 'production'
NPM_CONFIG_LOGLEVEL = 'error'
NODE_OPTIONS = '--max-old-space-size=2048' 