[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = [
    # Only install production dependencies for runtime
    'npm ci --omit=dev --prefer-offline --no-audit --no-fund'
]

[phases.build]
cmds = [
    # Install all dependencies for build
    'npm ci --prefer-offline --no-audit --no-fund',
    # Build the app
    'npm run build',
    # Remove dev dependencies after build
    'npm prune --production'
]

[start]
cmd = 'pm2-runtime start ecosystem.config.js'

[variables]
NODE_ENV = 'production'
NPM_CONFIG_LOGLEVEL = 'error' 