# Nixpacks will be used automatically when this section is commented out
# Nixpacks is much faster than Docker for Railway deployments
#
# [build]
# builder = "DOCKERFILE"
# dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/api/health"
healthcheckTimeout = 60 