# [build]
# builder = "DOCKERFILE"
# dockerfilePath = "Dockerfile"
# 
# Uncomment above to use Docker. By default, Railway will use nixpacks which is faster.

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/api/health"
healthcheckTimeout = 60 